[build]
builder = "NIXPACKS"
buildCommand = "npm ci"

[deploy]
startCommand = "node railway-server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production" 